services:
  mongo1:
    image: mongo:4.4
    container_name: mongo1
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example    
    volumes:
      - ./scripts:/scripts
    ports:
      - 27017:27017
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs" ]
    networks:
      - mongo-cdc-network

  mongoclient:
    container_name: "mongoclient"
    image: mongoclient/mongoclient:latest
    restart: always
    depends_on:
      - mongo1
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb://mongo1:27017
    networks:
      - mongo-cdc-network

networks:
  mongo-cdc-network:
    name: mongo-cdc-network
    driver: bridge