version: '3.1'

services:
  mongo1:
    image: mongo:4.4
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example    
    volumes:
      - ./scripts:/scripts
    ports:
      - 27017:27017
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs" ]
    networks:
      - mongo-cdc-network

  mongo2:
    image: mongo:4.4
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example    
    volumes:
      - ./scripts:/scripts
    ports:
      - 27018:27017
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs" ]
    networks:
      - mongo-cdc-network

  # mongo-express:
  #   image: mongo-express:latest
  #   restart: always
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: example
  #     ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo1:27017/
  #   networks:
  #     - mongo-cdc-network

networks:
  mongo-cdc-network:
    name: mongo-cdc-network
    driver: bridge